defaults:
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none
version: 2024-03-27-1.1.0
parameter:
    dataset_path: none
    checkpoint_path: ./checkpoint/training
    ocr_path: none
    device: gpu
    batch_size: 48
    num_workers: 16
    reference_count: 30
    generator:
        learning_rate: 1e-4
        loss_function:
            weight_adversarial: 1
            weight_classification: 1
            weight_structure: 0.8
            weight_style: 6.5
            weight_reconstruction: 20
    discriminator:
        learning_rate: 5e-5
        loss_function:
            weight_adversarial: 1
            weight_classification: 1
    num_iterations: 20000
    report_interval: 50
    save_interval: 500
    device_ids: [0,1]
    is_continue: False
    continue_pth: none



